# Generated by Django 5.0.4 on 2024-05-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(upload_to='images/')),
                ('ten_san_pham', models.CharField(max_length=100)),
                ('gia_ban', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_luong', models.IntegerField()),
                ('ten_shop', models.CharField(max_length=50)),
            ],
        ),
    ]
