# Generated by Django 5.0.4 on 2024-05-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_dat_hang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='so_luong',
            field=models.PositiveIntegerField(),
        ),
    ]
