# Generated by Django 5.0.4 on 2024-05-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trang_dat_hang', '0002_alter_sanpham_so_luong'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='trang_thai',
            field=models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('dong_y', 'Đồng ý'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=10),
        ),
    ]
